### ISSUE TITLE
error on `yarn start`

### ISSUE THREAD

**Issue by davibe** [joseluisq/preact-starter#1]
```
dade@choo:~/work/preact-starter(master)$ yarn start
yarn start v0.21.3
$ yarn clean
yarn clean v0.21.3
[1/2] Creating ".yarnclean"...
[2/2] Cleaning modules...
info Removed 0 files
info Saved 0 MB.
✨  Done in 1.15s.
$ parcel public/index.html 
(node:84699) UnhandledPromiseRejectionWarning: Error: Cannot find module './assets/RawAsset'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/dade/work/preact-starter/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/dade/work/preact-starter/node_modules/parcel-bundler/src/Parser.js:2:18)
    at Module._compile (/Users/dade/work/preact-starter/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:84699) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84699) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 1.83s.
dade@choo:~/work/preact-starter(master)$ 
```

**Comment by joseluisq** [comment]
Please check out [this thread](https://github.com/parcel-bundler/parcel/issues/1508).

**yarn**: v1.7
**node**: v10.6.0

```sh
~ yarn start
~ yarn run v1.7.0
$ yarn clean
$ rm -rf dist .cache
$ parcel public/index.html
Server running at http://localhost:1234
✨  Built in 4.47s.
```
